[project]
name = "inspireserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.13.0",
    "numpy>=2.3.2",
    "sentence-transformers>=5.1.0",
    "torch>=2.8.0",
]


[project.script]
main="main.py"
